---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: default
  labels:
    app: postgres
data:
  POSTGRES_DB: pocdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  